name: Swift

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  spm:
    name: Test with SPM
    runs-on: macos-latest    
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.3.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: SPM Test
        run: swift test -c debug
